### PR TITLE
Intrinsic kt powheg

### PR DESCRIPTION
**Pull request by smrenna**
This is a change to the treatment of primordial KT for LHE events.
In this case, it is possible to only use the hard primordial KT, since scalup is sometimes quite low and does not represent the hardness of the Born level process.

### CODE REVIEW

**Comment by bendavid** [comment]
Is this the right branch or should it be "cms/243" ?

**Comment by smuzaffar** [comment]
Master us not the right branch, which cmssw release this should go in?

**Comment by smrenna** [comment]
I defer to Josh.

**Comment by bendavid** [comment]
Needed in 10_6 for UL production,( but I guess it has to go in cmssw master first if that hasn't already moved to Pythia 8.3?)

**Comment by smuzaffar** [comment]
10.6 is using 240 , so please use cms/240 branch. Yes master is already using pythia 8 3, so no need to get it in master, unless this is new fux which is not part of 3

**Comment by bendavid** [comment]
Ok I think we should put this in both 240 and 243 then in anticipation that 10_6 might update to 243

**Comment by smuzaffar** [comment]
@smrenna , I tried to change the base branch to cms/240 but looks like this does not work as there is no common commit bwteen your feature branch anc cms/240. Can you please open two new PRs, one for cms/240 and one for cms/243?

**Comment by smrenna** [comment]
Hi, Malik,

Could you spell out the git commands I need to use?
These were my previous steps:

git clone git@github.com:cms-externals/pythia8<mailto:git@github.com:cms-externals/pythia8>
cd pythia8
git remote add smrenna git@github.com:smrenna/pythia8
[work on branch]
git push smrenna my_branch

**Comment by smuzaffar** [comment]
Hi,
Just use " -b cms/240" option with your git clone command.

Cheers, shahzad



-------- Original message --------

**Pull request closed without merging**
