### PR TITLE
Pythia Update to fix tau decays

### PR DESCRIPTION
**Pull request by Saptaparna**
The tau patch has been implemented that includes changes to:  src/HelicityMatrixElements.cc
and src/TauDecays.cc

The details of the bug are here: https://gitlab.com/Pythia8/releases/-/issues/155

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#8139

**Comment by agrohsje** [comment]
I see in the patched file:
// Copyright (C) 2019 Philip Ilten, Torbjorn Sjostrand.
pointing to 2019. Is the patch really based on P8.307 ? 
It would be irrelevant for the above but this seems to affect other places as well, e.g. 
limitTau0     = settingsPtr->flag("ParticleDecays:limitTau0");
  tau0Max       = settingsPtr->parm("ParticleDecays:tau0Max");
  limitTau      = settingsPtr->flag("ParticleDecays:limitTau");
  tauMax        = settingsPtr->parm("ParticleDecays:tauMax");
  limitRadius   = settingsPtr->flag("ParticleDecays:limitRadius");
  rMax          = settingsPtr->parm("ParticleDecays:rMax");
  limitCylinder = settingsPtr->flag("ParticleDecays:limitCylinder");
  xyMax         = settingsPtr->parm("ParticleDecays:xyMax");
  zMax          = settingsPtr->parm("ParticleDecays:zMax");
  Could it be that this is for an older version or so. I would assume the changes to be significantly less than this commit.

**Comment by agrohsje** [comment]
While I wrote the above, the checks "finished". They point to the same direction: 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-707b35/28475/cmsswtoolconf.log

**Comment by Saptaparna** [comment]
Ok, let me ask the authors then.

**Comment by Saptaparna** [comment]
It seems the patch was for 8.307 though.

**Comment by agrohsje** [comment]
Can you point to the original patch? I don't see why the time stamp should say 2019 if this is 8.307. 
I just checked P8.240 and I see this kind of statements: 
limitTau0     = settingsPtr->flag("ParticleDecays:limitTau0");
which looks exactly like what you have in the modified version and which seems incompatible with P8.307.

**Comment by Saptaparna** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/8139

**Comment by Saptaparna** [comment]
@agrohsje updated the PR -- now the correct timestamp shows up. I did nothing differently with the patch -- basically did a re-patch now. Hopefully, this will work.

**Comment by sihyunjeon** [comment]
@Saptaparna Hi sapta,
I don't think the timestamp change (2021->2022) here will make any difference to the test result (will be shocked if it did actually). The failure is from the compilation issue which is not really relevant to the commented lines in the code. Is the patch you have here based on 8.307?

The patch in [1] (@agrohsje FYI) is only touching several blocks and I would assume Philip gave us the patch based on 8.307 and this doesn't change too many things as here. How did you test things originally before making this PR?

[1] https://gitlab.com/Pythia8/releases/-/issues/155

**Comment by agrohsje** [comment]
Thanks Sihyun! In case the problems with the patch persists, let me know and I will check.

**Comment by Saptaparna** [comment]
Well, the timestamp statement was only in response to @agrohsje. The code has changed too. I ran local tests by updating the `/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/pythia8/306-84a4765a9948f9c1a5e66f80618e2c6d` with my local version of pythia8307.

**Comment by agrohsje** [comment]
What Sihyun means is that only the time stamp is changing, nothing else: 
image_2022_10_24T19_26_19_842Z

**Comment by agrohsje** [comment]
Let me know if I should upate @Saptaparna ?

**Comment by sihyunjeon** [comment]
I think the point of timestamp, that Alexander pointed out, was that this PR already seems a bit fishy "starting from the timestamp". Not that the timestamp itself is an issue.

If your patch was based on 8.30X there is no reason for the timestamp to revert back to 2019 from 2021. There are multiple changes in pointer and variable definitions that modifies the codes totally. Also these changes look like a bit beyond the scope of what Philip provided us. Can you double check if your patch base is really 8.30X?

And yes, as Alexander posted with screenshot - the fix you've made after Alexander's comment was only changing the lines which are in comments block that won't/shouldn't change the result of compilation.

Is this the same patch that worked for you when testing things locally?

**Comment by sihyunjeon** [comment]
Wow this is very puzzling it did go through. I am totally lost now. For example, I am not sure why this has changes for [1] to [2] included in this pull request. [1] is line in 8.2xx and [2] is the corresponding lines in 8.3xx. The default cms-externals was wrong in the first place (not up to date with 8.3xx)?  @agrohsje  (SORRY FALSE ALARM - I mixed up with the other git commit histories - commented again below)

[1] https://gitlab.com/Pythia8/releases/-/blob/pythia8244/src/TauDecays.cc#L84-92
[2] https://gitlab.com/Pythia8/releases/-/blob/pythia8306/src/TauDecays.cc#L77-85

**Comment by Saptaparna** [comment]
I am surprised too -- checking.

**Comment by sihyunjeon** [comment]
No wait I totally misunderstood what you've done @Saptaparna 

So this is nothing else other than changing the time stamp (2021->2022). None of the fixes are applied here. So that's why compilation was successful - it's a null pull request that doesn't change anything.

I checked Philips patch file and the changes he made isn't included here

**Comment by Saptaparna** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/8139

**Comment by menglu21** [comment]
> No wait I totally misunderstood what you've done @Saptaparna
> 
> So this is nothing else other than changing the time stamp (2021->2022). None of the fixes are applied here. So that's why compilation was successful - it's a null pull request that doesn't change anything.
> 
> I checked Philips patch file and the changes he made isn't included here

since Sapta already included the patch, just put the link of the patch here, https://gitlab.com/Pythia8/releases/-/issues/155#note_1054685915

**Comment by agrohsje** [comment]
Thanks Sapta! This looks good to me now. It seems you applied the patch to 8.307  and not the branch. But doesn't matter as the actual code is the same compared to 8.306. Thanks!

**Comment by menglu21** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Comment by Saptaparna** [comment]
> Thanks Sapta! This looks good to me now. It seems you applied the patch to 8.307 and not the branch. But doesn't matter as the actual code is the same compared to 8.306. Thanks!

Indeed. I did that to be expedient as that is the setup I had locally. I think next time I will directly apply the patch.

**Pull request merged**
