### PR TITLE
slha-multiple-reinitializations

### PR DESCRIPTION
**Pull request by smrenna**
…iple reinits

### CODE REVIEW

**Comment by smrenna** [comment]
Backporting of changes to SLHA interface that allows for multiple init calls to pythia (thereby changing the min/max values for resonances).

**Comment by menglu21** [comment]
@cmsbuild please test

**Comment by menglu21** [comment]
@smuzaffar is it supposed to test with a specific release

**Comment by sarafiorendi** [comment]
hi, a kind request to try to include this PR as soon as possible, it is needed for the production of samples for analyses which are already pre-approved. thanks!

**Comment by menglu21** [comment]
@cmsbuild please test

**Comment by menglu21** [comment]
@cmsbuild please test for CMSSW_10_6_X/slc7_amd64_gcc700

**Comment by mmasciov** [comment]
A gentle ping.
Let me stress that this PR should be considered **very urgent**, since the lack of this fix is holding an increasing number of MC requests, for an increasing number of analyses.
Thanks!

**Comment by fwyzard** [comment]
Just a suggestion, but maybe improving the title and the description of the PR could help.

**Comment by fwyzard** [comment]
And also fixing the tests... is `test_MpsWorkFlow` relevant ?

**Comment by menglu21** [comment]
> Just a suggestion, but maybe improving the title and the description of the PR could help.

Hi @fwyzard  , the purpose of this PR is 
"applied patch to handle min/max values of resonance masses after multiple reinits.
Explicit checks are made to guarantee that the minimum value sampled for a resonance mass
is below the nominal mass. This is relevant when the slha information is updated in Pythia and
an existing pythia instance is re-initialized." which is in PR https://github.com/cms-externals/pythia8/pull/31. Is it necessary to change the title, if yes, @smrenna please modify the title.

as for the test, tbh I'm not sure whether the release is needed. The error https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-eec6f6/39894/unitTests/src/Alignment/MillePedeAlignmentAlgorithm/test/test_MpsWorkFlow/testing.log should be irrelevant to the modification to me

**Comment by menglu21** [comment]
urgent

**Comment by menglu21** [comment]
let's try another test, if the error is still there but not related to the change, I suggest we can merge this PR

**Comment by menglu21** [comment]
@cmsbuild please test

**Comment by menglu21** [comment]
Hi @smuzaffar @fwyzard there is error "IOError: [Errno 2] No such file or directory: 'src/Alignment/MillePedeAlignmentAlgorithm/templates/universalConfigTemplate.py'" in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-eec6f6/39894/unitTests/src/Alignment/MillePedeAlignmentAlgorithm/test/test_MpsWorkFlow/testing.log, but I don't think the pythia8 change will cause this error. do you know how this happened. Since this PR is needed urgently by the analysis, how should we proceed

**Comment by smuzaffar** [comment]
correct , `test_MpsWorkFlow` failure is not related to this change. This is because 10.6.X is missing https://github.com/cms-sw/cmssw/commit/6bd5d30d0b2c625ad9a3e35531d65e3d35435b9f fix

**Comment by smuzaffar** [comment]
+externals

these changes are backported from python 8.311 release https://gitlab.com/Pythia8/releases/-/commit/001b35e1f9ba95cb9dc5e212635a4fdadc614b21

**Comment by smuzaffar** [comment]
> @cmsbuild please test

`please test` by default runs tests for development CMSSW release cycle i.e. 14.1.X at this time. This PR should be tested for CMSSW_10_6_X. so using `please for for CMSSW_10_6_X` is the correct way to test it

**Comment by smuzaffar** [comment]
I am merging it and opening a cmsdist PR to include it for 10.6.X

**Pull request merged**
