### PR TITLE
Changes to Info class so that weights do now grow with every re-init

### PR DESCRIPTION
**Pull request by smrenna**
Chris Jones convinced me to do a pull request instead ;).;

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by fabiocos** [comment]
@smrenna do you consider this as a fix to be integrated in future pythia8 releases?

**Comment by smrenna** [comment]
Yes, I did a merge request on pythia82 yesterday.   I will provide more information when/if it is available.

We are hoping that our next major release is pythia83, and I also made a merge request there.

Steve

**Comment by fabiocos** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
