### PR TITLE
Heavyothermatching Update

### PR DESCRIPTION
**Pull request by smrenna**
Fix bug that treated the Z0 like a parton.

### CODE REVIEW

**Comment by bendavid** [comment]
Fixes a problem observed in 800pre2 relvals.

**Comment by covarell** [comment]
+1

**Comment by ghost** [comment]
+1
Tested locally. Will make CMSDIST PR as well for 80X.

**Comment by bendavid** [comment]
did this ever actually make it into 80x?

**Comment by smuzaffar** [comment]
@bendavid , does not look like. @degano was there any thing holding up cms-sw/cmsdist#2050

**Pull request merged**
