### PR TITLE
Fix all uninitialized member variables [226]

### PR DESCRIPTION
**Pull request by kpedro88**
Port of #12 to the older version. Similar problems have started to arise in 7_1_43_patch1, though they do not occur in 7_1_38_patch1. Some change in externals moved stack memory around so uninitialized member variables that were serendipitously `false` are now `true`.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@smuzaffar @mrodozov how can I make this test against 7_1_X?

**Comment by kpedro88** [comment]
please test for CMSSW_7_1_X

**Comment by smuzaffar** [comment]
please test with cms-sw/cms-bot#1222 for CMSSW_7_1_X
@kpedro88 , testing external only working with newer tag of PKGTOOLS. 71X is using an old tag V00-31-XX. cms-sw/cms-bot#1222 forces to use newer pkgtools.

**Comment by smuzaffar** [comment]
please test with cms-sw/cms-bot#1222 for CMSSW_7_1_X

**Comment by smuzaffar** [comment]
@kpedro88 , looks like pkgtools V00-32-XX does not work for old release cycle. The only way to test this is to merge it (may be to a cms/226x  branch first)  and then test it via cmsdist PR

**Comment by smuzaffar** [comment]
I have moved this PR to be on cms/226x. I will merge it and create a cmsdist PR to test it.

**Pull request merged**
