### PR TITLE
Fix all uninitialized member variables

### PR DESCRIPTION
**Pull request by kpedro88**
I ran the clang-tidy check `cppcoreguidelines-pro-type-member-init` on the entire pythia8 code base. This creates initializer lists in constructors for all POD types to avoid uninitialized member variables. A version of this patch has been submitted to pythia8 upstream and will hopefully be included in the next public release (whatever comes after 8.235).

resolves https://github.com/cms-sw/cmssw/issues/22214
(among other things)

### CODE REVIEW

**Comment by smrenna** [comment]
Hi, it is not clear that this patch will 100 percent go into the Pythia8 trunk.  I suggest adding only what is really necessary at this point.    It has been useful NOT having these fixes to sniff out certain problems.

**Comment by kpedro88** [comment]
Please keep us updated, but it's very painful for central production to have to fix these one at a time.

**Comment by smuzaffar** [comment]
assign orp
please sign it so that we can merge and update cmsdist

**Comment by kpedro88** [comment]
@smuzaffar it was already merged by @mrodozov

**Comment by smuzaffar** [comment]
oops, I should go to sleep then :-)
thanks

**Pull request merged**
