### PR TITLE
Heavyothermatching

### PR DESCRIPTION
**Pull request by smrenna**

### CODE REVIEW

**Comment by smrenna** [comment]
Modified SlowJet base code so that data is protected.
JetMatching now handles partons marked as heavy or other differently.

**Comment by bendavid** [comment]
@degano can we have this in CMSSW 80x now?

**Comment by ghost** [comment]
@smrenna @bendavid I'll test this now.

**Comment by ghost** [comment]
+1
Tested here: https://github.com/cms-sw/cmsdist/pull/1951

**Pull request merged**
