### PR TITLE
BeamRemnants update for LHE events in 230

### PR DESCRIPTION
**Pull request by mseidel42**
Backport of https://github.com/cms-externals/pythia8/pull/24

Needed for W mass samples in CMSSW 9_4_X

@smrenna

### CODE REVIEW

**Comment by mseidel42** [comment]
@smrenna, @smuzaffar, @mrodozov ping

**Comment by smuzaffar** [comment]
please test for CMSSW_9_4_X

**Comment by smuzaffar** [comment]
assign generators

**Comment by agrohsje** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
