### PR TITLE
modifications to allow heavy/other matching

### PR DESCRIPTION
**Pull request by smrenna**

### CODE REVIEW

**Comment by ghost** [comment]
@smrenna the code you provided is wrong. The class you specify that inherits from `Pythia8::SlowJet` uses the private member of its base class as its own (e.g. line 50: `if (clSize > 0) {`) which is not allowed (the members should be protected in the base class for that to be correct).
Also you should probably consider to deploy such a consistent code in a standalone c++ source file rather than one big header, also to make it easy to debug while compiling.
Please also remove the commented code.

**Comment by bendavid** [comment]
@degano we want to use this for testing physics for now.  It will eventually go back upstream anyways.
As long as it compiles and doesn't break anything I would be inclined to go ahead.

**Comment by ghost** [comment]
@bendavid unfortunately it does actually breaks everything the moment GeneratorInterface/Pythia8Interface include the chain of headers in a source file that gets compiled...

**Comment by bendavid** [comment]
Ah ok, in that case @smrenna can you try to fix it?  (At least the private vs protected issue).  Leaving the code in the header is I think fine for the moment.

**Comment by bendavid** [comment]
@degano can you please comment further?

**Comment by ghost** [comment]
@bendavid @smrenna Yes, so the new class introduced in the header file of this PR `HJSlowJet` inherits from `SlowJet` defined in pythia8/Analysis.h: https://github.com/cms-externals/pythia8/blob/08f43c3a6110675bcd9a249f035abd5b751dab0b/include/Pythia8/Analysis.h#L414.
The issue causing the problem is that `HJSlowJet` uses some datamember (e.g. Line 50 `if (clSize > 0) {`) of `SlowJet` that are defined by private here: https://github.com/cms-externals/pythia8/blob/08f43c3a6110675bcd9a249f035abd5b751dab0b/include/Pythia8/Analysis.h#L530.
The issue only becomes apparent when compiling `GeneratorInterface/Pythia8Interface` against this PR because in Pythia8 itself there is no source code which gets compiled that includes this header file (or a chain leading to it).
Which also brings the question: how this code was ever tested?...

**Comment by smrenna** [comment]
Got it.  I reread p228-229 of "Accelerated C++".  I have to change
clSize to protected in the base class.

I tested this in stand-alone Pythia8, never with Pythia8Interface.

Thanks,
Steve

**Comment by ghost** [comment]
@smrenna Yes, that should work, however take care, the reason why the issue does not arise when compiling Pythia8 standalone is simply because this header does not get called in any compiled source code (eg .cc files etc...). To check that it compiles and does indeed what you expect I'd suggest you to create a simple test implementing a main() c++ function that instantiate this class and makes some trivial check over it.

**Comment by smrenna** [comment]
When I said I "tested in stand-alone Pythia8," this means that it 
compiles and
runs cleanly with our standard main89.cc example.   This is why I 
thought there
would be no problem with the Pythia8Interface.

**Comment by smrenna** [comment]
Alas, I _had_ changed Analysis.h, but forgot to check it in!
So I do know some C++ ....

Sorry for the spam.

--Steve

**Pull request closed without merging**
