### PR TITLE
I modified the JetMatching.h plugin to handle colored SUSY particles

### PR DESCRIPTION
**Pull request by smrenna**
in a similar manner as for the Top quark.   As long as QED radiation
for TimeShower was disabled, test LHE files with tops and stops interchanged
behaved identically.   I also updated other parts of JetMatching.h to
match the current Pythia8 plugin (except for commenting out the use of
one Pythia parameter that doesn't exist in the current CMS version).
I have _NOT_ tested the treatment of quarks whose scale is set to
the beam energy.

### CODE REVIEW

**Comment by bendavid** [comment]
@covarell @govoni
This fixes a critical issue with jet matching in events with sparticles (CMSSW 71x,74x,76x is ok, this is only related to the latest changes in 80x), so needed for SUSY fastsim production in 80x.

**Comment by covarell** [comment]
Hi @bendavid , @smrenna 
No objections of course, but I think we should take a decision on Pythia8 for 80X.
We have this patch + heavy and "other" matching on top of 8.212, in the meantime 8.215 is out. Should we have @mkirsano update Pythia8 and try to merge these changes in, or do you prefer to keep it branched in CMSSW for now?

**Comment by bendavid** [comment]
In my opinion it would be nice to get a working version in 80x first before trying to update to 8.215.

**Comment by covarell** [comment]
Ok

**Comment by covarell** [comment]
+1

**Comment by ghost** [comment]
+1
Tested compilation locally.

**Pull request merged**
